version: '3.6'

services: 

  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qg
    
volumes:
  dbdata: 